n = int(input('\033[34mDigite um número:\033[m'))
c = dict(l='\033[m', azul='\033[34m', amarelo='\033[33m', corirada='\033[4;30;45m')
print('-' * 20)
print('A tabuada de {} é:'.format(c['azul'] + str(n) + c['l']))
print('{} X {:2} = {}{}'.format(n, 1, c['azul'], n * 1, c['l']))
print('{} X {:2} = {}{}'.format(n, 2, c['azul'], n * 2, c['l']))
print('{} X {:2} = {}{}'.format(n, 3, c['azul'], n * 3, c['l']))
print('{} X {:2} = {}{}'.format(n, 4, c['azul'], n * 4, c['l']))
print('{} X {:2} = {}{}'.format(n, 5, c['azul'], n * 5, c['l']))
print('{} X {:2} = {}{}'.format(n, 6, c['azul'], n * 6, c['l']))
print('{} X {:2} = {}{}'.format(n, 7, c['azul'], n * 7, c['l']))
print('{} X {:2} = {}{}'.format(n, 8, c['azul'], n * 8, c['l']))
print('{} X {:2} = {}{}'.format(n, 9, c['azul'], n * 9, c['l']))
print('{} X {:2} = {}{}'.format(n, 10, c['azul'], n * 10, c['l']))
print('-' * 20)
