X = input('Digite alguma coisa: ')
print('O tipo primitivo é ',type(X))
print('É Alfanumérico?',X.isalnum())
print('É Alfabetico?',X.isalpha())
print('É um número decimal?',X.isdecimal())
print('É minusculo?',X.islower())
print('É maiusculo',X.isupper())
print('Somente espaços?',X.isspace())
print('É um digito?',X.isdigit())
print('Pode ser impresso?',X.isprintable())
print('É um identificador?',X.isidentifier())
print('Digitado {}'.format(X))
print('Está capitalizada?',X.istitle())