n1 = int(input('Insira um número: '))
n2 = int(input('Insira outro número: '))
a = (n1+n2)
s = (n1-n2)
m = (n1*n2)
d = (n1/n2)
e = (n1**n2)
di = (n1//n2)
print('a soma é {},\n o produto é {} e a \n divisão é {:.3}'.format(a,m,d), end='')
print('Divisão inteira {} e potência {}'.format(di,e))